[package]
name = "warp_subscriptions"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
env_logger = "0.8.2"
futures = "0.3.12"
log = "0.4.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-stream = "0.1.3"
tokio = { version = "1.2.0", features = ["rt", "rt-multi-thread", "macros"] }
warp = "0.3.0"

juniper = { path = "../../juniper" }
juniper_graphql_ws = { path = "../../juniper_graphql_ws" }
juniper_warp = { path = "../../juniper_warp", features = ["subscriptions"] }
