[package]
name = "juniper_codegen_tests"
version = "0.1.0"
publish = false
edition = "2018"

[dependencies]
juniper = { path = "../../juniper" }
futures = "0.3.15"

[dev-dependencies]
serde_json = "1.0.64"
tokio = { version = "1.7.1", features = ["rt", "time", "macros"] }
trybuild = "1.0.42"
